# Generated by Django 5.2.6 on 2026-03-30 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('session', '0008_mockpreset_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Cancelled')], db_index=True, default=1)),
                ('requested_date', models.DateField()),
                ('comment', models.TextField(blank=True)),
                ('rejection_comment', models.TextField(blank=True)),
                ('availability_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='scheduling.availabilityslot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests_as_candidate', to=settings.AUTH_USER_MODEL)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests_as_examiner', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_request', to='session.ieltsmocksession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
