# Generated by Django 5.2.6 on 2026-03-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic_number']},
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='QuestionSet',
        ),
    ]
