# Generated by Django 5.2.6 on 2026-03-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_add_topic_number'),
    ]

    def backfill(apps, schema_editor):
        Topic = apps.get_model("questions", "Topic")
        for topic in Topic.objects.filter(topic_number__isnull=True):
            topic.topic_number = topic.pk
            topic.save(update_fields=["topic_number"])

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
