# Generated by Django 5.2.6 on 2026-03-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_backfill_topic_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['part', 'topic_number']},
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('part', 'topic_number')},
        ),
    ]
