# Generated by Django 5.2.6 on 2026-03-25 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topic_number_unique_per_part'),
    ]

    def rebackfill(apps, schema_editor):
        Topic = apps.get_model("questions", "Topic")
        # Temporarily clear all topic_numbers to avoid unique_together conflicts while reassigning
        Topic.objects.update(topic_number=None)
        # For each part, assign 1..N ordered by pk
        for part in Topic.objects.values_list("part", flat=True).distinct():
            for i, topic in enumerate(
                Topic.objects.filter(part=part).order_by("pk"), start=1
            ):
                Topic.objects.filter(pk=topic.pk).update(topic_number=i)

    operations = [
        migrations.RunPython(rebackfill, migrations.RunPython.noop),
    ]
