# Generated by Django 5.2.6 on 2026-03-25 00:44

import session.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_sessionresult_overall_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ieltsmocksession',
            name='invite_token',
            field=models.CharField(default=session.models._generate_invite_token, editable=False, max_length=9, unique=True),
        ),
    ]
