# Generated by Django 5.2.6 on 2026-04-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_sessionshare'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criterionscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='criterionscore',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Examiner'), (2, 'AI')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='criterionscore',
            unique_together={('session_result', 'criterion', 'source')},
        ),
        migrations.CreateModel(
            name='AIFeedbackJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Done'), (4, 'Failed')], db_index=True, default=1)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback_jobs', to='session.ieltsmocksession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
