# Generated by Django 5.2.6 on 2026-04-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0010_criterionscore_source_aifeedbackjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='aifeedbackjob',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
