# Generated by Django 5.2.5 on 2026-03-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_guest_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_sessions',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Examiner'), (2, 'Candidate')], default=1),
        ),
    ]
