# Generated by Django 5.2.6 on 2026-03-30 06:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_is_verified_alter_user_max_sessions_and_more'),
        ('session', '0008_mockpreset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_sessions',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('target_speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('current_speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExaminerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('full_legal_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +998XXXXXXXXX', regex='^\\+998\\d{9}$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('is_verified', models.BooleanField(default=False, help_text='IELTS examiner verification badge (admin-managed). Not to be confused with User.is_verified which is email verification.')),
                ('completed_session_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examiner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExaminerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('reading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('writing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('examiner_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='main.examinerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_band', models.DecimalField(decimal_places=1, max_digits=3)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='main.candidateprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history_entries', to='session.ieltsmocksession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('candidate_profile', 'session')},
            },
        ),
    ]
